name: SST
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write
  contents: read

env:
  SST_STAGE: ${{ github.ref == 'refs/heads/main' && 'prod' || github.head_ref }}

jobs:
  DeployApp:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::496131963451:role/GitHub
          role-duration-seconds: 3600
          aws-region: us-east-1
      - name: Generate stage name
        run: |
          SST_STAGE=${SST_STAGE//\//-}
          echo "SST_STAGE=$SST_STAGE" >> $GITHUB_ENV
      - name: Install dependencies
        run: npm i
      - name: Install SST
        run: curl -fsSL https://ion.sst.dev/install | bash
      - name: Deploy app
        run: sst deploy --stage ${{ env.SST_STAGE }}
