name: Continuous Integration

on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Run unit and integration tests
      run: npm run test

    - name: Generate code coverage report
      run: npm run test:coverage 

    - name: Start the application
      run: npm start &
    
    - name: Execute end-to-end tests
      run: npm run test:e2e 
