name: Paw

on:
  push:
    branches: [ "main", "session-10-Assignment" ]
  pull_request:
    branches: [ "main", "john-royal:main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the PR
      uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Install Dependencies
      run: |
        npm install
        npm ci
     
    - name: Install playwright
      run: npx playwright install --with-deps
    
    - name: Building the Application
      run: npm run build
